name: Upload Existing Armbian Image

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Upload existing Armbian image
      uses: actions/upload-artifact@v4
      with:
        name: armbian-image
        path: armbian-build/output/images/*.img
